services:
    catalogdb:
        image: mongo:latest

    identitydb:
        image: mcr.microsoft.com/mssql/server:2019-latest
            
    basketdb:
        image: redis:latest
           
    discountdb:
        image: postgres:latest
           
    orderdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
                 
    rabbitmq:
        image: rabbitmq:3.12.2-management

volumes:
  catalogdb_volume:
  discountdb_volume:
  identitydb_volume:
  orderdb_volume:
