services:
    mongodb:
        container_name: microservices-practice-mongodb
        image: mongo:latest
        environment:
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        - GOSU_VERSION=1.16
        - JSYAML_VERSION=3.13.1
        - MONGO_PACKAGE=mongodb-org
        - MONGO_REPO=repo.mongodb.org
        - MONGO_MAJOR=6.0
        - MONGO_VERSION=6.0.5
        - HOME=/data/db
        ports:
            - "27017:27017"
        volumes:
            - mongodb_db:/data/db
            - mongodb_configdb:/data/configdb
            
    identitydb:
        container_name: microservices-practice-identitydb
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=Password12*
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        ports:
            - "1433:1433"
        volumes:
            - mongodb_db:/data/db
            - mongodb_configdb:/data/configdb
            
volumes:
  mongodb_db:
  mongodb_configdb: